version: '3.2'

services:

  frontend:
    build:
      context: ./server/frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./server:/app

  backend:
    build:
      context: ./server/backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./server:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=tasktracker
      - MYSQL_USER=tasktracker
      - MYSQL_PASSWORD=secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    links:
      - mysql:db

  migrate:
    build:
      context: ./server/backend
    command: sh -c "
      apt-get update && apt-get install -y netcat && 
      
      while ! nc -z mysql 3306; do sleep 1; done &&
      php yii migrate --interactive=0 && 
      php yii migrate --migrationPath=@yii/rbac/migrations --interactive=0 && 
      php yii rbac/init"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./server:/app
    depends_on:
      - frontend
      - backend
      - mysql
      - phpmyadmin
